# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20141204130418) do

  create_table "admins", :force => true do |t|
    t.string   "username"
    t.string   "password"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "agents", :force => true do |t|
    t.integer  "client_id"
    t.string   "company_name"
    t.string   "broker_name"
    t.string   "title"
    t.string   "address"
    t.string   "city"
    t.string   "state"
    t.string   "zip_code"
    t.string   "home_phone"
    t.string   "home_extension"
    t.string   "direct_phone"
    t.string   "mobile_phone"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "notify_agent"
    t.string   "email"
  end

  create_table "client_executives", :force => true do |t|
    t.integer "client_id"
    t.integer "executive_id"
    t.integer "share_percentage"
    t.integer "share_value"
  end

  create_table "clients", :force => true do |t|
    t.integer  "user_id"
    t.string   "company_name"
    t.string   "client_name"
    t.string   "title"
    t.string   "address"
    t.string   "city"
    t.string   "state"
    t.string   "zip_code"
    t.string   "home_phone"
    t.string   "home_extension"
    t.string   "direct_phone"
    t.string   "mobile_phone"
    t.string   "fax_number"
    t.string   "email_address"
    t.text     "special_instructions"
    t.string   "shipping_company_name"
    t.string   "shipping_attention"
    t.string   "shipping_address"
    t.string   "shipping_city"
    t.string   "shipping_state"
    t.string   "shipping_zip_code"
    t.string   "shipping_courier"
    t.string   "shipping_account_number"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "shipping_same_as_contact_info"
    t.string   "attachment_1_file_name"
    t.string   "attachment_1_content_type"
    t.integer  "attachment_1_file_size"
    t.datetime "attachment_1_updated_at"
    t.string   "attachment_2_file_name"
    t.string   "attachment_2_content_type"
    t.integer  "attachment_2_file_size"
    t.datetime "attachment_2_updated_at"
    t.string   "attachment_3_file_name"
    t.string   "attachment_3_content_type"
    t.integer  "attachment_3_file_size"
    t.datetime "attachment_3_updated_at"
    t.string   "attachment_4_file_name"
    t.string   "attachment_4_content_type"
    t.integer  "attachment_4_file_size"
    t.datetime "attachment_4_updated_at"
    t.string   "attachment_5_file_name"
    t.string   "attachment_5_content_type"
    t.integer  "attachment_5_file_size"
    t.datetime "attachment_5_updated_at"
    t.string   "attachment_6_file_name"
    t.string   "attachment_6_content_type"
    t.integer  "attachment_6_file_size"
    t.datetime "attachment_6_updated_at"
    t.string   "name"
    t.string   "bank"
    t.string   "routing"
    t.string   "account"
    t.string   "routing_confirmation"
    t.string   "account_confirmation"
    t.decimal  "customer_fee",                  :precision => 8, :scale => 2
  end

  create_table "credits", :force => true do |t|
    t.integer  "user_id"
    t.integer  "credits"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "total_credits"
  end

  create_table "executives", :force => true do |t|
    t.string  "name"
    t.string  "address"
    t.string  "city"
    t.string  "state"
    t.string  "account_name"
    t.string  "account_type"
    t.string  "account_holder_type"
    t.integer "account_number"
    t.integer "routing_number"
  end

  create_table "flycredits", :force => true do |t|
    t.string "promocode", :limit => 40
  end

  create_table "invoices", :force => true do |t|
    t.integer "client_id"
    t.string  "promo_code"
  end

  create_table "messages", :force => true do |t|
    t.integer  "user_id"
    t.integer  "recipient_id"
    t.integer  "order_id"
    t.string   "title"
    t.text     "body"
    t.boolean  "is_unread"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "attachment_file_name"
    t.string   "attachment_content_type"
    t.integer  "attachment_file_size"
    t.datetime "attachment_updated_at"
    t.boolean  "hide_from_sender"
    t.string   "attachment_1_file_name"
    t.string   "attachment_1_content_type"
    t.integer  "attachment_1_file_size"
    t.datetime "attachment_1_updated_at"
    t.string   "attachment_2_file_name"
    t.string   "attachment_2_content_type"
    t.integer  "attachment_2_file_size"
    t.datetime "attachment_2_updated_at"
    t.string   "attachment_3_file_name"
    t.string   "attachment_3_content_type"
    t.integer  "attachment_3_file_size"
    t.datetime "attachment_3_updated_at"
    t.string   "attachment_4_file_name"
    t.string   "attachment_4_content_type"
    t.integer  "attachment_4_file_size"
    t.datetime "attachment_4_updated_at"
    t.string   "attachment_5_file_name"
    t.string   "attachment_5_content_type"
    t.integer  "attachment_5_file_size"
    t.datetime "attachment_5_updated_at"
    t.string   "attachment_6_file_name"
    t.string   "attachment_6_content_type"
    t.integer  "attachment_6_file_size"
    t.datetime "attachment_6_updated_at"
  end

  create_table "multiple_notaries", :force => true do |t|
    t.integer  "order_id"
    t.integer  "notary_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "status"
    t.boolean  "accept_status", :default => false
    t.integer  "mail_count",    :default => 0
    t.boolean  "notification",  :default => false
  end

  create_table "notaries", :force => true do |t|
    t.integer  "user_id"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "company_name"
    t.string   "day_phone"
    t.string   "evening_phone"
    t.string   "mobile_phone"
    t.string   "work_phone"
    t.string   "fax_number"
    t.string   "fee_single_loan_overnight"
    t.string   "fee_single_loan_email"
    t.string   "fee_1st_and_2nd_overnight"
    t.string   "fee_1st_and_2nd_email"
    t.string   "notary_commision_number"
    t.string   "notary_commision_number_expiration_date"
    t.string   "e_and_o_insurance"
    t.string   "e_and_o_insurance_amount"
    t.string   "e_and_o_insurance_expiration_date"
    t.string   "weekday_deliver_address"
    t.string   "weekday_deliver_city"
    t.string   "weekday_deliver_state"
    t.string   "weekday_deliver_zip_code"
    t.string   "weekend_deliver_address"
    t.string   "weekend_deliver_city"
    t.string   "weekend_deliver_state"
    t.string   "weekend_deliver_zip_code"
    t.string   "billing_payable_to"
    t.string   "billing_deliver_address"
    t.string   "billing_deliver_city"
    t.string   "billing_deliver_state"
    t.string   "billing_deliver_zip_code"
    t.string   "email_document_capability"
    t.string   "laser_printer"
    t.string   "printer_paper_type"
    t.string   "enotarization_capability"
    t.string   "own_a_copier"
    t.string   "notary_history_length"
    t.string   "notarize_loan_documents"
    t.string   "notarized_documents_count"
    t.string   "title_insurance_provider"
    t.string   "bilingual"
    t.string   "bilingual_language"
    t.string   "refinance"
    t.string   "purchases"
    t.string   "lines_of_credit"
    t.string   "power_of_attorney"
    t.string   "sellers_packaging"
    t.string   "reverse_mortgage"
    t.text     "comments"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "is_attorney"
    t.string   "work_extension"
    t.string   "photo_file_name"
    t.string   "photo_content_type"
    t.integer  "photo_file_size"
    t.datetime "photo_updated_at"
    t.float    "lat"
    t.float    "lng"
    t.boolean  "on_vacation"
    t.string   "certified_signing_agent"
    t.string   "life_settlement_experience"
    t.text     "notes"
    t.string   "w_9"
    t.string   "name"
    t.string   "bank"
    t.string   "routing"
    t.string   "account"
    t.string   "commercial_loan"
    t.string   "billingual_language_1"
    t.string   "account_type"
    t.string   "account_holder_type"
    t.integer  "fee"
    t.string   "fee_type"
    t.string   "w9_info"
    t.integer  "travel_distance"
  end

  create_table "notes", :force => true do |t|
    t.integer  "order_id"
    t.text     "notes"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "user_id"
  end

  create_table "order_attachments", :force => true do |t|
    t.integer  "order_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "data_file_name"
    t.string   "data_content_type"
    t.integer  "data_file_size"
    t.datetime "data_updated_at"
  end

  create_table "order_executives", :force => true do |t|
    t.integer "order_id"
    t.integer "executive_id"
  end

  create_table "order_feedbacks", :force => true do |t|
    t.integer  "notary_id"
    t.integer  "client_id"
    t.string   "accuracy"
    t.string   "communication"
    t.string   "punctuality"
    t.string   "overall"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "order_id"
    t.string   "fees"
    t.string   "professionalism"
    t.text     "comments"
    t.string   "response_from_notary"
    t.decimal  "overall_rating",         :precision => 5, :scale => 2
    t.boolean  "notaryflyu_test"
    t.string   "client_professionalism"
    t.string   "status_update"
    t.string   "doc_issue"
    t.string   "satisfaction"
  end

  create_table "orders", :force => true do |t|
    t.integer  "client_id"
    t.integer  "notary_id"
    t.integer  "broker_id"
    t.string   "loan_number"
    t.date     "signing_date"
    t.string   "signing_time"
    t.string   "loan_type"
    t.integer  "sets_of_docs"
    t.string   "shipped_via"
    t.string   "tracking_number"
    t.string   "required_language"
    t.boolean  "attorney_required"
    t.boolean  "title_producer_required"
    t.string   "borrower_1_work_phone"
    t.string   "borrower_1_extension"
    t.string   "borrower_1_home_phone"
    t.string   "borrower_1_mobile_phone"
    t.string   "borrower_2_work_phone"
    t.string   "borrower_2_extension"
    t.string   "borrower_2_home_phone"
    t.string   "borrower_2_mobile_phone"
    t.string   "signing_location_address"
    t.string   "signing_location_city"
    t.string   "signing_location_state"
    t.string   "signing_location_zip_code"
    t.text     "special_instructions"
    t.string   "return_company_name"
    t.string   "return_attention"
    t.string   "return_address"
    t.string   "return_city"
    t.string   "return_state"
    t.string   "return_zip_code"
    t.string   "return_account_number"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "status"
    t.string   "delivery_options"
    t.string   "return_shipping_courier"
    t.string   "notary_fee"
    t.integer  "agent_id"
    t.string   "closed_carrier"
    t.string   "closed_tracking_number"
    t.text     "closed_comments"
    t.string   "order_notary_name"
    t.string   "order_notary_company_name"
    t.string   "order_notary_contact_address"
    t.string   "order_notary_contact_city"
    t.string   "order_notary_contact_state"
    t.string   "order_notary_contact_zip_code"
    t.string   "order_notary_home_phone"
    t.string   "order_notary_mobile_phone"
    t.string   "order_notary_work_phone"
    t.string   "order_notary_work_extension"
    t.string   "order_notary_fax_number"
    t.string   "order_notary_email_address"
    t.string   "order_notary_payment_address"
    t.string   "order_notary_payment_city"
    t.string   "order_notary_payment_state"
    t.string   "order_notary_payment_zip_code"
    t.string   "order_notary_fee"
    t.string   "order_attachment_1_file_name"
    t.string   "order_attachment_1_content_type"
    t.integer  "order_attachment_1_file_size"
    t.datetime "order_attachment_1_updated_at"
    t.string   "order_attachment_2_file_name"
    t.string   "order_attachment_2_content_type"
    t.integer  "order_attachment_2_file_size"
    t.datetime "order_attachment_2_updated_at"
    t.string   "order_attachment_3_file_name"
    t.string   "order_attachment_3_content_type"
    t.integer  "order_attachment_3_file_size"
    t.datetime "order_attachment_3_updated_at"
    t.string   "order_attachment_4_file_name"
    t.string   "order_attachment_4_content_type"
    t.integer  "order_attachment_4_file_size"
    t.datetime "order_attachment_4_updated_at"
    t.string   "order_attachment_5_file_name"
    t.string   "order_attachment_5_content_type"
    t.integer  "order_attachment_5_file_size"
    t.datetime "order_attachment_5_updated_at"
    t.string   "order_attachment_6_file_name"
    t.string   "order_attachment_6_content_type"
    t.integer  "order_attachment_6_file_size"
    t.datetime "order_attachment_6_updated_at"
    t.string   "feedback"
    t.string   "borrower_1_first_name"
    t.string   "borrower_1_last_name"
    t.string   "borrower_2_first_name"
    t.string   "borrower_2_last_name"
    t.integer  "re_confirmation",                                               :default => 0
    t.string   "doc_delivery_address_option"
    t.string   "attachment_1_file_name"
    t.string   "attachment_1_file_url"
    t.string   "attachment_2_file_name"
    t.string   "attachment_2_file_url"
    t.string   "attachment_3_file_name"
    t.string   "attachment_3_file_url"
    t.string   "attachment_4_file_name"
    t.string   "attachment_4_file_url"
    t.string   "attachment_5_file_name"
    t.string   "attachment_5_file_url"
    t.string   "attachment_6_file_name"
    t.string   "attachment_6_file_url"
    t.text     "cancel_order"
    t.string   "status_timeline"
    t.date     "cancel_order_date"
    t.text     "admin_cancel_description"
    t.text     "admin_order_cancel"
    t.date     "admin_order_cancel_date"
    t.integer  "admin_approve"
    t.string   "travel_fee"
    t.date     "order_notary_fee_date"
    t.text     "other_fee_reason"
    t.text     "total_revenue"
    t.integer  "signing_fee"
    t.integer  "sample"
    t.text     "signing_comments"
    t.integer  "attachments_count"
    t.boolean  "payment",                                                       :default => false
    t.datetime "payment_date"
    t.datetime "client_payment_date"
    t.string   "cc_email"
    t.decimal  "customer_fee",                    :precision => 8, :scale => 2
    t.boolean  "move_to_order_history_by_admin",                                :default => false
  end

  create_table "passwords", :force => true do |t|
    t.integer  "user_id"
    t.string   "reset_code"
    t.datetime "expiration_date"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "promocodes", :force => true do |t|
    t.string "promocode", :limit => 40
    t.string "credits",   :limit => 40
  end

  create_table "users", :force => true do |t|
    t.string   "login",                     :limit => 100
    t.string   "name",                      :limit => 100, :default => ""
    t.string   "email",                     :limit => 100
    t.string   "crypted_password",          :limit => 40
    t.string   "salt",                      :limit => 40
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "remember_token",            :limit => 40
    t.datetime "remember_token_expires_at"
    t.string   "user_type"
    t.string   "steps"
    t.string   "user_password"
    t.datetime "user_signin"
    t.integer  "suspend"
  end

  add_index "users", ["login"], :name => "index_users_on_login", :unique => true

end
